---
- name: Install and Config server
  hosts: ansibledyanmic
  tasks:
  - name: Install java
    apt:
      name: nginx
      state: present
      update_cache: yes
    become: yes  
  - name: start nginx server
    service:
      name: nginx 
      state: started
    become: yes  